Update Bookworm upstream sources

diff --git a/ddm-mx/ddm-mx b/ddm-mx/ddm-mx
--- a/ddm-mx/ddm-mx
+++ b/ddm-mx/ddm-mx
@@ -21,8 +21,9 @@
 source /usr/local/lib/cli-shell-utils/cli-shell-utils.bash
 source gettext.sh
 DEBIAN_VERSION_CODENAME=$(grep VERSION_CODENAME /etc/os-release|cut -d"=" -f2)
+DEBIAN_VERSION_NUMBER=$(cat /etc/debian_version  |cut -d"." -f1)
 
-VERSION="23.07.01"
+VERSION="23.12.01"
 ME=${0##*/}
 CLI_PROG="ddm-mx"
 LOCK_FILE="/run/lock/$CLI_PROG"
@@ -31,22 +32,31 @@ LOG="/var/log/ddm.log"
 BP_REPO="$DEBIAN_VERSION_CODENAME-backports"
 BP_REPO_ADDRESS="deb http://ftp.debian.org/debian"
 MX_TEST_REPO_ADDRESS="deb http://la.mxrepo.com/mx/testrepo/ $DEBIAN_VERSION_CODENAME test"
+NVIDIA_DIRECT_REPO_ADDRESS="deb [signed-by=/usr/share/keyrings/cuda-archive-keyring.gpg] https://developer.download.nvidia.com/compute/cuda/repos/debian$DEBIAN_VERSION_NUMBER/x86_64/ /"
 BACKPORTS_OVERRIDE=false
+NVIDIA_OVERRIDE=false
 
 export TEXTDOMAINDIR=/usr/share/locale 
 export TEXTDOMAIN="ddm-mx"
 
+#blanket error message
 UNKNOWN_ERROR=$(eval_gettext "Unknown error")
+#error for options
 OPTION_ERROR1=$(eval_gettext "Option-")
+#tell that option needs an arguement
 OPTION_ERROR2=$(eval_gettext "requires an argument.")
+#must run as root or elevated
 RUN_AS_ROOT=$(eval_gettext "Run as root")
+#say what we are installing drivers for
 INSTALL_DRIVERS_FOR=$(eval_gettext "Install drivers for: ")
 
 NVIDIA_XCONFIG="nvidia-xconfig"
 
 ARCH=$(dpkg --print-architecture)
 
+#desktop name
 DESKTOPFILENAME=$(gettext "Nvidia driver installer")
+#desktop comment
 DESKTOPFILECOMMENT=$(gettext "Install proprietary nvidia driver from repo")
 
 main(){
@@ -71,7 +81,7 @@ PURGE=''
 INSTALL=''
 FORCEDRIVER=''
 TEST=false
-while getopts ":f:bi:p:htd:c" opt; do
+while getopts ":f:bNi:p:htd:c" opt; do
   case $opt in
     h)
       usage HELP
@@ -96,8 +106,12 @@ while getopts ":f:bi:p:htd:c" opt; do
       PCIID="$OPTARG"
       ;;
     b)
-      # Testing
+      # off debian backports repo
       BACKPORTS_OVERRIDE=true
+      ;;
+     N)
+      #offer nvidia developer repo 
+      NVIDIA_OVERRIDE=true
       ;;
     c) #force create of 20-nvidia.conf file
     	create_20_nvidiaconf
@@ -121,6 +135,7 @@ while getopts ":f:bi:p:htd:c" opt; do
     *)
       # Unknown error: start GUI
       #launch_gui $@
+      #not a legal option
       echo $(eval_gettext "Invalid option") | tee -a $LOG
       exit 0
       ;;
@@ -179,7 +194,9 @@ echo "===================================" | tee -a $LOG
 for DRV in $PURGE; do
   # Start the log
   echo "===================================" | tee -a $LOG
+ #apt purge of drivers specified
   echo $(eval_gettext "Purge drivers for: ")$DRV | tee -a $LOG
+ #times stamp.  starting at this day and time
   echo $(eval_gettext "Start at (m/d/y):") $(date +"%m/%d/%Y %H:%M:%S") | tee -a $LOG
   echo "===================================" | tee -a $LOG
   
@@ -187,7 +204,7 @@ for DRV in $PURGE; do
     nvidia)
       install_open
       ;;
-    *)
+    *)#unknown option
       echo $(eval_gettext 'ERROR: Unknown argument: $DRV') | tee -a $LOG
       echo
       usage
@@ -242,6 +259,7 @@ function usage() {
   echo $(gettext "The following options are allowed:")
   echo
   echo "-b            " $(gettext "Offer debian-backports alternative")
+  echo "-N            " $(gettext "Offer Nvidia developer repo alternative")
   echo "-c            " $(gettext "Create 20-nvidia.conf")
   echo
   echo "-i [driver]   " $(gettext "Install given driver.")
@@ -274,6 +292,9 @@ function usage() {
 # nvidia -------------------------------------------------------------------------
 
 function preseed_nvidia {
+	if [ $TEST  ]; then
+		return
+	fi
   CANDIDATE=$1
   echo 'nvidia-support nvidia-support/check-xorg-conf-on-removal boolean false' | debconf-set-selections
   echo 'nvidia-support nvidia-support/check-running-module-version boolean true' | debconf-set-selections
@@ -326,20 +347,19 @@ function install_nvidia {
   check_cand
   
 if [ "$BUMBLEBEE_NVIDIA_VERSION" = "nvidia-legacy-340xx-driver" ] ; then   
+#error message about when bumblebee drivers can be used
 		echo $(eval_gettext "Unsupported configuration.  bumblebee only works with 390xx drivers and up.") |tee $LOG
 		my_exit
 fi
 
   MAIN_CAND=$CANDIDATE
   MAIN_NVIDIA=$NVIDIA_VERSION
-  if [ "$DISTRIB_ID" = "MX" ]; then
-    if [ "$BACKPORTS_OVERRIDE" = "true" ]; then
-        debian_backports_dialog
-    else
-        mx_test_repo_dialog
-    fi
+  if [ "$BACKPORTS_OVERRIDE" = "true" ]; then
+	debian_backports_dialog
   else
-    debian_backports_dialog
+	if [ "$NVIDIA_OVERRIDE" = "true" ]; then
+		nvidia_repo_dialog
+	fi
   fi
   
   echo ""
@@ -358,14 +378,18 @@ fi
   
   check_legacy
   
+  #installed hardware requires this driver
   echo $(eval_gettext "Need driver: ")$DRIVER "$CANDIDATE" $BUMBLEBEE_NVIDIA_VERSION "$NVIDIA_VERSION" | tee -a $LOG
 
   set_packages 
   
+  #we are going to install this package 
   echo $(eval_gettext "NVIDIA packages to install are ") $DRIVER | tee -a $LOG
 
+#keep going
   YES_no $(eval_gettext "Continue?")
-    if [ "$?" = "1" ]; then 
+    if [ ! "$?" = "0" ]; then 
+		clean_up
         exit 0
     fi
  
@@ -385,6 +409,7 @@ fi
   # Install the packages
   echo "Frontend: $(echo $DEBIAN_FRONTEND)" | tee -a $LOG
 
+  #the nvidia install command will be presented here for the log
   echo $(eval_gettext "Nvidia command ") "= apt-get install --install-recommends --reinstall -y $FORCE $SWITCH $BP $DRIVER" | tee -a $LOG
   apt-get install --reinstall -y linux-headers-$(uname -r) build-essential $TESTSWITCH 2>&1 | tee -a $LOG
   apt-get install --reinstall $INSTALL_RECOMMENDS -y $SWITCH $BP $DRIVER $TESTSWITCH 2>&1 | tee -a $LOG
@@ -448,7 +473,7 @@ fi
   	fi
   	#update initramfs one more time
   	
-  	update-initramfs -u -k all | tee -a $LOG
+  	update_initramfs
   fi
   echo $(eval_gettext "Finished") | tee -a $LOG
   echo ""
@@ -469,6 +494,7 @@ function purge_proprietary_drivers {
   # remove possible leftover symlinks
 	remove_modprobe_symlinks
   if [ "$?" = "0" ]; then 
+      #success in removing proprietary drivers and returning to open source drivers
       echo $(eval_gettext "Proprietary drivers removed") | tee -a $LOG
   fi
 }
@@ -482,10 +508,12 @@ function install_open {
   # Install the packages
   update_sources
   echo "Frontend: $(echo $DEBIAN_FRONTEND)" | tee -a $LOG
+  #the command to restore open source drivers presented for the log
   echo $(eval_gettext "Open command ") "= apt-get install --reinstall -y $FORCE $DRIVER" | tee -a $LOG
   apt-get install --reinstall $FORCE $DRIVER 2>&1 | tee -a $LOG
   
   if [ "$?" = "0" ]; then 
+      #success at installing open source drivers
       echo $(eval_gettext "Open drivers installed") | tee -a $LOG
   fi
   
@@ -500,6 +528,7 @@ echo "" | tee -a $LOG
 echo "" | tee -a $LOG 
 if [ -f /etc/apt/sources.list.d/debian-backports-temp.list ]; then
   rm -f /etc/apt/sources.list.d/debian-backports-temp.list
+  #return sources to a state before this application made any changes
   echo $(eval_gettext "Resetting sources")
   apt-get update
   echo ""
@@ -509,6 +538,22 @@ if [ -f /etc/apt/sources.list.d/mx-test-repo-temp.list ]; then
     echo $(eval_gettext "Resetting sources")
     apt-get update
     echo ""
+fi
+if [ -f /etc/apt/sources.list.d/nvidia-repo-temp.list ]; then
+    rm -f /etc/apt/sources.list.d/nvidia-repo-temp.list
+    echo $(eval_gettext "Resetting sources")
+    apt-get update
+    echo ""
+fi
+#only cleanup nvidia sources if the -N switch was used
+if [ "$NVIDIA_OVERRIDE" = "true" ]; then
+  if [ -f /etc/apt/sources.list.d/cuda-debian$DEBIAN_VERSION_NUMBER-x86_64.list ]; then
+    echo $(eval_gettext "Resetting sources")
+    apt purge cuda-keyring -y
+    rm -f /etc/apt/sources.list.d/cuda-debian$DEBIAN_VERSION_NUMBER-x86_64.list
+    apt-get update
+    echo ""
+  fi
 fi
 
 ##re-enable nvidia-peristenced availability
@@ -537,6 +582,7 @@ enable_debian_backports()
   update_sources
   echo ""
   if [ "$ARCH" = "amd64" ]; then
+    #inform we are updating nvidia-detect package
     echo $(eval_gettext "Installing latest nvidia-detect package")|tee -a $LOG
     echo ""
     apt-get install $SWITCH $BP nvidia-detect |tee -a $LOG  
@@ -558,6 +604,37 @@ enable_mx_test_repo()
     apt-get install $SWITCH "$BP" nvidia-detect |tee -a $LOG  
     echo ""
   fi
+}
+
+enable_nvidia_repo()
+{
+#enabling nvidia-direct repo
+  echo $(eval_gettext "Enabling Nvidia developer repo")
+  #getting the nvidia gpg archive key
+  echo $(eval_gettext "Getting Nvidia repo signing key")
+  NVIDIA_KEY_ADDRESS="https://developer.download.nvidia.com/compute/cuda/repos/debian$DEBIAN_VERSION_NUMBER/x86_64/cuda-keyring_1.1-1_all.deb"
+  echo $NVIDIA_KEY_ADDRESS
+  wget $NVIDIA_KEY_ADDRESS -O /tmp/nvidia-keyring.deb
+  dpkg -i /tmp/nvidia-keyring.deb
+  rm /tmp/nvidia-keyring.deb
+  if [ $? = 0 ]; then
+       echo $(eval_gettext "Running apt-get update...")
+  else
+  	   #problem downloading and installing the nvidia gpg key package
+       echo $(eval_gettext "Error downloading nvidia direct repo key")
+       return
+  fi
+
+  update_sources
+  echo ""
+ #don't install nvidia-detect with nvidia developer repo...depends causes problems with existing nvidia packages
+ #if [ "$ARCH" = "amd64" ]; then
+ #  echo $(eval_gettext "Installing latest nvidia-detect package")|tee -a $LOG
+ #  echo ""
+ #  apt-get install $SWITCH "$BP" nvidia-detect |tee -a $LOG  
+ #
+ #  echo ""
+ #fi
 }
 
 debian_backports_dialog()
@@ -601,9 +678,27 @@ yes_NO "$(eval_gettext "Would you like to check MX Test Repo for a later version
         esac
 }
 
+nvidia_repo_dialog()
+{
+echo $(eval_gettext "Would you like to check the Nvidia developer repo for a later version?") >> $LOG
+yes_NO "$(eval_gettext "Would you like to check the Nvidia developer repo for a later version?")"
+
+        case $? in
+           0)   echo $(eval_gettext "Ok")...| tee -a $LOG 
+                SWITCH=""
+                BP=""
+                enable_nvidia_repo	;;
+           1)   echo $(eval_gettext "Ok")... | tee -a $LOG
+                SWITCH=""
+                BP=""           ;;
+           *) echo $(eval_gettext "invalid option.")  $(eval_gettext "exiting")... | tee -a $LOG && exit 0;;
+        esac
+}
+
 
 which_driver()
 {
+#a choice of driver versions is being offerred
 echo $(eval_gettext "Which driver do you wish to install") | tee -a $LOG
         echo "" | tee -a $LOG
         echo $(eval_gettext "Main repos or debian-backports?") | tee -a $LOG
@@ -627,6 +722,7 @@ echo $(eval_gettext "Which driver do you wish to install") | tee -a $LOG
               #replace nvidia-detect from main repo
               #only install if nvidia-detect was present already (not present on 32 bit systems)
               if [ "$ARCH" = "amd64" ]; then
+                #put nvidia-detect back to version in current enabled repos
               	echo $(eval_gettext "Reset nvidia-detect") | tee -a $LOG
               	apt-get remove nvidia-detect -y && apt-get install nvidia-detect -y                     
               fi
@@ -680,6 +776,44 @@ echo $(eval_gettext "Which driver do you wish to install") | tee -a $LOG
         esac
 }
 
+which_driver_nvidia()
+{
+echo $(eval_gettext "Which driver do you wish to install") | tee -a $LOG
+        echo "" | tee -a $LOG
+        echo $(eval_gettext "Main repos or Nvidia direct repo") | tee -a $LOG
+        echo "" | tee -a $LOG
+        echo 1: $(eval_gettext "Main") $DRIVER $MAIN_CAND $BUMBLEBEE_NVIDIA_VERSION $MAIN_NVIDIA| tee -a $LOG
+        echo "" | tee -a $LOG
+        echo 2: $(eval_gettext "Nvidia Direct") $DRIVER $CANDIDATE $BUMBLEBEE_NVIDIA_VERSION $NVIDIA_VERSION| tee -a $LOG
+        echo "" | tee -a $LOG
+	echo 3: $(eval_gettext "Exit") | tee -a $LOG
+        echo "" | tee -a $LOG
+        echo $(eval_gettext "Enter Number of selection") | tee -a $LOG
+        read -n 1 -e x
+
+        case $x in
+           1) echo $(eval_gettext "Ok")...| tee -a $LOG 
+                SWITCH=""
+                BP=""
+                NVIDIA_VERSION=$MAIN_NVIDIA
+                apt purge -y cuda-keyring
+                apt-get update
+                #replace nvidia-detect from main repo
+                #only install if nvidia-detect was present already (not present on 32 bit systems)
+                if [ "$ARCH" = "amd64" ]; then
+                	echo $(eval_gettext "Reset nvidia-detect") | tee -a $LOG
+                	apt-get remove nvidia-detect -y && apt-get install nvidia-detect -y
+                fi
+                ;;
+           2)   echo $(eval_gettext "Ok")... | tee -a $LOG
+                ;;
+                
+           3) echo $(eval_gettext "exiting") |tee -a $LOG && exit 0;;
+
+           *) echo $(eval_gettext "invalid option.")  $(eval_gettext "exiting")... | tee -a $LOG && exit 0;;
+        esac
+}
+
 
 check_cand()
 {
@@ -711,13 +845,14 @@ update_sources()
             echo $(eval_gettext 'There was a problem with the apt-get update.  See $LOG for details') | tee -a $LOG
             echo ""
             echo ""
-            my_exit
+			my_exit
         fi
     fi
 }
 
 purge_message()
 {
+#provide user with information on going back to open source drivers
 local PURGE_MESSAGE=$(eval_gettext "To restore open source drivers use:  ")
 echo ""| tee -a $LOG
 echo "========================================"| tee -a $LOG
@@ -747,9 +882,11 @@ echo "========================================"| tee -a "$USER_HOME_PATH"
 echo "========================================"| tee -a "$USER_HOME_PATH"
 echo ""| tee -a "$USER_HOME_PATH"
 echo ""| tee -a "$USER_HOME_PATH"
+#provide user with information on where file with recovery command is stored
 echo $(eval_gettext "For recovery help see ") | tee -a "$USER_HOME_PATH"
 echo "https://mxlinux.org/wiki/hardware/nvidia-driver-install-recovery" | tee -a "$USER_HOME_PATH"
 echo ""
+#provide user with information on where file with recovery command is stored
 echo $(eval_gettext "Information written to ")"$USER_HOME_PATH"
 chown $USER:$USER "$USER_HOME_PATH"
 
@@ -757,6 +894,9 @@ chown $USER:$USER "$USER_HOME_PATH"
 
 nvidia-340-fix()
 {
+if [ $TEST  ]; then
+	return
+fi
 # backup libglx.so
 local lib_version
 lib_version=$(LANG=C apt-cache policy nvidia-legacy-340xx-driver |grep Candidate |cut -d: -f2|cut -d. -f2|cut -d- -f1)
@@ -772,6 +912,9 @@ fi
 
 nvidia-340-reverse-fix()
 {
+if [ $TEST  ]; then
+	return
+fi
 	# if backup libglx.so exists, then revert it back.  this will take place just before reinstallation of the open drivers.
 if [ -L /usr/lib/xorg/modules/extensions/libglx.so ]; then
 	if [ -f /usr/lib/xorg/modules/extensions/libglx.so.bak ]; then
@@ -786,13 +929,12 @@ fi
 check_source_install(){
 	#check for possible source install
   if [ -e /usr/bin/nvidia-installer ]; then
+    #found an installation from source
     echo $(eval_gettext "Possible previous install from source or smxi/sgfxi detected.") | tee -a $LOG
     echo $(eval_gettext "Version detected: ") $(modinfo nvidia | grep ^version: | sed 's/[^0-9.]*//g') | tee -a $LOG
     echo $(eval_gettext "Latest possible with this script : ") $CANDIDATE | tee -a $LOG
+    #please remove the source installation if you wish to use ddm-mx
     echo $(eval_gettext "Please remove with  <sudo nvidia-install --uninstall> and reboot if you wish to proceed") | tee -a $LOG
-    #if [ $GUI ]; then
-	#	echo "$(eval_gettext 'Possible previous install from source or smxi/sgfxi detected.')" "$(eval_gettext 'Please remove with  <sudo nvidia-install --uninstall> and reboot if you wish to proceed')" > /tmp/ddm-msg
-	#fi
 	exit 10
   fi
 }
@@ -804,9 +946,11 @@ check_optimus(){
     if [ -z "$FORCEDRIVER" ]; then
 		if lspci -vnn | grep Intel |grep -q 0300 ; then
 			if lspci -vnn | grep NVIDIA | grep -q 0302 ; then
+			    #possible hybrid graphics detected
 				echo $(eval_gettext "nvidia-optimus detected") | tee -a $LOG
 				OPTIMUS=2
 			else
+			    #ask if this system has hybrid graphics
 				YES_no "$(eval_gettext "Is this a NVIDIA/INTEL Optimus system?")"
 				if [ "$?" = "0" ]; then
 					OPTIMUS=2
@@ -978,8 +1122,11 @@ set_packages(){
 
 choose_cand(){
 	if [ -f /etc/apt/sources.list.d/debian-backports-temp.list ]; then
+	   #candidate from enabled repos
        echo $(eval_gettext "Main repo candidate is:  ") $MAIN_CAND |tee -a $LOG
+       #candidate from debian backports repo
        echo $(eval_gettext "Debian backports candidate is:  ")  $CANDIDATE |tee -a $LOG
+       #installed version, if any
        echo $(eval_gettext "Installed is: ") $INSTALLED | tee -a $LOG
        echo ""
        which_driver
@@ -988,12 +1135,22 @@ choose_cand(){
   
   if [ -f /etc/apt/sources.list.d/mx-test-repo-temp.list ]; then
        echo $(eval_gettext "Main repo candidate is:  ") $MAIN_CAND |tee -a $LOG
+       #test repo candidate
        echo $(eval_gettext "MX Test repo candidate is:  ")  $CANDIDATE |tee -a $LOG
        echo $(eval_gettext "Installed is: ") $INSTALLED | tee -a $LOG
        echo ""
        which_driver_mx
        echo ""
   fi  
+  if [ -f /etc/apt/sources.list.d/cuda-debian$DEBIAN_VERSION_NUMBER-x86_64.list ]; then
+       echo $(eval_gettext "Main repo candidate is:  ") $MAIN_CAND |tee -a $LOG
+       #Nvidia developer repo candidate here
+       echo $(eval_gettext "Nvidia developer repo candidate is:  ")  $CANDIDATE |tee -a $LOG
+       echo $(eval_gettext "Installed is: ") $INSTALLED | tee -a $LOG
+       echo ""
+       which_driver_nvidia
+       echo ""
+  fi 
 }
 
 confirm_reinstall(){
@@ -1056,6 +1213,9 @@ create_modprobe_symlinks(){
 	#/etc/modprobe.d/nvidia-blacklists-nouveau.conf
     #/etc/modprobe.d/nvidia-modprobe.conf
     #/etc/modprobe.d/nvidia-options.conf
+    if [ $TEST  ]; then
+		return
+	fi
     
     if [ ! -e /etc/modprobe.d/nvidia-blacklists-nouveau.conf ]; then
 		ln -s /etc/nvidia/current/nvidia-blacklists-nouveau.conf /etc/modprobe.d/nvidia-blacklists-nouveau.conf
@@ -1078,6 +1238,9 @@ remove_modprobe_symlinks(){
 }
 
 create_20_nvidiaconf(){
+	if [ $TEST  ]; then
+		return
+	fi
 	sudo tee /etc/X11/xorg.conf.d/20-nvidia.conf <<!
 Section "Device"
      Identifier "Nvidia Card"
@@ -1089,6 +1252,9 @@ EndSection
 }
 
 remove_20_nvidiaconf(){
+	if [ $TEST  ]; then
+		return
+	fi
     echo "rm 20-nvidia.conf" | tee -a $LOG
 	if [ -e /etc/X11/xorg.conf.d/20-nvidia.conf ]; then
 		rm --force /etc/X11/xorg.conf.d/20-nvidia.conf
@@ -1113,6 +1279,15 @@ nvidia_driver_override(){
        *) echo $(eval_gettext "invalid option.")  $(eval_gettext "exiting")... | tee -a $LOG && exit 0;;
     esac
     echo ""
+}
+
+update_initramfs()
+{
+if [ $TEST  ]; then
+	return
+fi
+	
+update-initramfs -u -k all | tee -a $LOG
 }
 
 main "$@"
